#language: es

Característica: Simulador Digicredito

  Antecedentes:
    Cuando se asigna el usuario
    Y ingresa su usuario 88776655 y contrasena 4112935

  @pruebaArchivo
  Esquema del escenario: prueba
    Entonces se ingresa el dato <Cedula>
    Ejemplos:
      |Cedula|Credito|oficinaAsesor|nombresApellidos|fechaNacimiento|celular|Correo|actividad|pagaduria|Contacto|montoSolicitado|Tasa|Plazo|DiasHabilesIntereses|descNomina|descLey|Ingresos|VlrCompraSaneamiento|lineaCredito|rutaPDF|estadoActual|page|codigo|primerNombre|segundoNombre|primerApellido|segundoApellido|NombreCredito|fechaExpedicion|genero|estrado|tipoVivienda|claseVivienda|posicionHogar|nivelEscolaridad|cuotaHipotecaria|tipoDocNomina|otrosIngresos|modalidadDesembolso|tipoCliente|paisNacimiento|lugarDeNacimiento|nacionalidad|estadoCivil|profesion|departamento|ciudad|direccionResidencia|mesesResidencia|numeroHijos|personasACargo|tipoPension|codigoProgramaNomina|fechaIngreso|fechaTerminacion|nitAfiliacion|tipoDocumento|cargo|nombreBeneficario|documentoBeneficiario|celularBeneficiario|monedaExtranjera|tipoTransanccion|productoBancario|banco|numProducto|tipoProducto|pais|ciudad|monto|moneda|funcionarioPublico|recursosPublicos|expuestoPoliticamente|fechaExpuesto|Mes|fecha|AnnoAfetacion|TipoDesen|fechaActual|Banco|NumRadicadoCredito|
     ##@externaldata@./src/test/resources/data/AutomationDataRetanqueo.xlsx@RetanqueoDigiCredito
      | "10092369" | "55857" | "Soacha"      | "JAIRO MENDOZA DIAZ" | "19/10/1952"    | "3183903022" | "aalvarez@excelcredit.co" | "Pensionado" | "P.A COLPENSIONES" | "Entidad donde trabaja" | "20000000" | "1.70" | "60"  | "100"                | "260000"   | "100000" | "5500000" | "300000"             | "Retanqueo compra de cartera" | "src/test/resources/Data/PDFPRUEBA.pdf" | "Pendientes por Radicar" | ""   | "12345" | "JAIRO"      | ""            | "MENDOZA"      | "DIAZ"          | "JAIRO"       | "18/01/1974"    | "F"    | "Estrato 1" | "Arriendo"   | "Casa"        | "Jefe de hogar" | "Universitario"  | "100000"         | "Desprendible de nómina" | "30000000"    | "Pago masivo (efectivo)" | "AAA"       | "colombia"     | "colombia"        | "colombiano" | "Soltera/o" | "ingeniero" | "Antioquia"            | "Abejorral"      | "Cra 14 No. 93a - 30" | "24"            | "2"         | "0"            | "pension"   | "123456"             | "01/01/2015" | "30/12/2022"     | "123456"      | "Certificación laboral" | "CEO" | "Luis Perez Ramirez" | "1234567890"          | "3183903022"        | "No"             | "Importaciones"  | "No"             | "Santander" | "966855"    | "Inversiones en oro" | "Alemania" | "Berlin" | "8500" | "Euros" | "No"               | "No"             | "No"                  | "12/12/2008"  | "Febrero" | "20/07/1963" | "2022"        | "Efectivo" | "16/02/2022" | "Bancolombia Remanentes - 60237038927 - REMANENTE" | null               |


  @Simulador
  Esquema del escenario:  Paso uno Datos cliente
    Entonces el usuario diligencias los campos del formulario <oficinaAsesor><nombresApellidos><Cedula><fechaNacimiento><celular><Correo><actividad><pagaduria><Contacto>
    Y ingresa la informacion de los valores credito a solicitar <montoSolicitado><Tasa><Plazo><DiasHabilesIntereses>
    Y diligencia los datos financieros <Ingresos><descLey><descNomina><lineaCredito><Credito><VlrCompraSaneamiento>
    Y se validan los campos del simulador <Tasa><Plazo><Ingresos><descLey><descNomina><pagaduria><DiasHabilesIntereses><Credito><VlrCompraSaneamiento><lineaCredito>
    Y se inicia la solicitud del credito
    Entonces El usuario carga los archivos imagen de la cedula del cliente <rutaPDF>
    Y realiza el registro del cliente paso 2 de 4 <Cedula><primerNombre><segundoNombre><primerApellido><segundoApellido><fechaNacimiento><fechaExpedicion><departamento><ciudad><genero>
    Y se llenan los datos adicionales <departamento><departamento>
    Entonces se realiza el proceso de Prospeccion del cliente <Cedula>
    Cuando busca el credito para retomar el estado actual <Cedula><estadoActual><page>
    Y recorre las paginas de la consulta de propeccion

    Ejemplos:
      |Cedula|Credito|oficinaAsesor|nombresApellidos|fechaNacimiento|celular|Correo|actividad|pagaduria|Contacto|montoSolicitado|Tasa|Plazo|DiasHabilesIntereses|descNomina|descLey|Ingresos|VlrCompraSaneamiento|lineaCredito|rutaPDF|estadoActual|page|codigo|primerNombre|segundoNombre|primerApellido|segundoApellido|NombreCredito|fechaExpedicion|genero|estrado|tipoVivienda|claseVivienda|posicionHogar|nivelEscolaridad|cuotaHipotecaria|tipoDocNomina|otrosIngresos|modalidadDesembolso|tipoCliente|paisNacimiento|lugarDeNacimiento|nacionalidad|estadoCivil|profesion|departamento|ciudad|direccionResidencia|mesesResidencia|numeroHijos|personasACargo|tipoPension|codigoProgramaNomina|fechaIngreso|fechaTerminacion|nitAfiliacion|tipoDocumento|cargo|nombreBeneficario|documentoBeneficiario|celularBeneficiario|monedaExtranjera|tipoTransanccion|productoBancario|banco|numProducto|tipoProducto|pais|ciudad|monto|moneda|funcionarioPublico|recursosPublicos|expuestoPoliticamente|fechaExpuesto|Mes|fecha|AnnoAfetacion|TipoDesen|fechaActual|Banco|NumRadicadoCredito|
     ##@externaldata@./src/test/resources/data/AutomationDataRetanqueo.xlsx@RetanqueoDigiCredito
      | "10092369" | "55857" | "Soacha"      | "JAIRO MENDOZA DIAZ" | "19/10/1952"    | "3183903022" | "aalvarez@excelcredit.co" | "Pensionado" | "P.A COLPENSIONES" | "Entidad donde trabaja" | "20000000" | "1.70" | "60"  | "100"                | "260000"   | "100000" | "5500000" | "300000"             | "Retanqueo compra de cartera" | "src/test/resources/Data/PDFPRUEBA.pdf" | "Pendientes por Radicar" | ""   | "12345" | "JAIRO"      | ""            | "MENDOZA"      | "DIAZ"          | "JAIRO"       | "18/01/1974"    | "F"    | "Estrato 1" | "Arriendo"   | "Casa"        | "Jefe de hogar" | "Universitario"  | "100000"         | "Desprendible de nómina" | "30000000"    | "Pago masivo (efectivo)" | "AAA"       | "colombia"     | "colombia"        | "colombiano" | "Soltera/o" | "ingeniero" | "Antioquia"            | "Abejorral"      | "Cra 14 No. 93a - 30" | "24"            | "2"         | "0"            | "pension"   | "123456"             | "01/01/2015" | "30/12/2022"     | "123456"      | "Certificación laboral" | "CEO" | "Luis Perez Ramirez" | "1234567890"          | "3183903022"        | "No"             | "Importaciones"  | "No"             | "Santander" | "966855"    | "Inversiones en oro" | "Alemania" | "Berlin" | "8500" | "Euros" | "No"               | "No"             | "No"                  | "12/12/2008"  | "Febrero" | "20/07/1963" | "2022"        | "Efectivo" | "16/02/2022" | "Bancolombia Remanentes - 60237038927 - REMANENTE" | null               |

  @endeudamientoGlobal
  Esquema del escenario: Diligencia los datos de endeudamiento global
    Cuando busca el credito para retomar el estado actual <Cedula><estadoActual><page>
    Y registra la informacion basica solicitante <codigo><estrado><tipoVivienda><claseVivienda><posicionHogar><nivelEscolaridad>
    Y registra la informacion financiera <descLey><descNomina>
    Entonces finaliza registrando la informacion a centrales <cuotaHipotecaria><tipoDocNomina><rutaPDF><otrosIngresos>

    Ejemplos:
      |Cedula|Credito|oficinaAsesor|nombresApellidos|fechaNacimiento|celular|Correo|actividad|pagaduria|Contacto|montoSolicitado|Tasa|Plazo|DiasHabilesIntereses|descNomina|descLey|Ingresos|VlrCompraSaneamiento|lineaCredito|rutaPDF|estadoActual|page|codigo|primerNombre|segundoNombre|primerApellido|segundoApellido|NombreCredito|fechaExpedicion|genero|estrado|tipoVivienda|claseVivienda|posicionHogar|nivelEscolaridad|cuotaHipotecaria|tipoDocNomina|otrosIngresos|modalidadDesembolso|tipoCliente|paisNacimiento|lugarDeNacimiento|nacionalidad|estadoCivil|profesion|departamento|ciudad|direccionResidencia|mesesResidencia|numeroHijos|personasACargo|tipoPension|codigoProgramaNomina|fechaIngreso|fechaTerminacion|nitAfiliacion|tipoDocumento|cargo|nombreBeneficario|documentoBeneficiario|celularBeneficiario|monedaExtranjera|tipoTransanccion|productoBancario|banco|numProducto|tipoProducto|pais|ciudad|monto|moneda|funcionarioPublico|recursosPublicos|expuestoPoliticamente|fechaExpuesto|Mes|fecha|AnnoAfetacion|TipoDesen|fechaActual|Banco|NumRadicadoCredito|
     ##@externaldata@./src/test/resources/data/AutomationDataRetanqueo.xlsx@RetanqueoDigiCredito
      | "10092369" | "55857" | "Soacha"      | "JAIRO MENDOZA DIAZ" | "19/10/1952"    | "3183903022" | "aalvarez@excelcredit.co" | "Pensionado" | "P.A COLPENSIONES" | "Entidad donde trabaja" | "20000000" | "1.70" | "60"  | "100"                | "260000"   | "100000" | "5500000" | "300000"             | "Retanqueo compra de cartera" | "src/test/resources/Data/PDFPRUEBA.pdf" | "Pendientes por Radicar" | ""   | "12345" | "JAIRO"      | ""            | "MENDOZA"      | "DIAZ"          | "JAIRO"       | "18/01/1974"    | "F"    | "Estrato 1" | "Arriendo"   | "Casa"        | "Jefe de hogar" | "Universitario"  | "100000"         | "Desprendible de nómina" | "30000000"    | "Pago masivo (efectivo)" | "AAA"       | "colombia"     | "colombia"        | "colombiano" | "Soltera/o" | "ingeniero" | "Antioquia"            | "Abejorral"      | "Cra 14 No. 93a - 30" | "24"            | "2"         | "0"            | "pension"   | "123456"             | "01/01/2015" | "30/12/2022"     | "123456"      | "Certificación laboral" | "CEO" | "Luis Perez Ramirez" | "1234567890"          | "3183903022"        | "No"             | "Importaciones"  | "No"             | "Santander" | "966855"    | "Inversiones en oro" | "Alemania" | "Berlin" | "8500" | "Euros" | "No"               | "No"             | "No"                  | "12/12/2008"  | "Febrero" | "20/07/1963" | "2022"        | "Efectivo" | "16/02/2022" | "Bancolombia Remanentes - 60237038927 - REMANENTE" | null               |

  @desembolso
  Esquema del escenario: Diligenciamiento del desembolso
    Cuando busca el credito para retomar el estado actual <Cedula><estadoActual><page>
    Y se selecciona la modalidad de desembolso y tipo de cliente <modalidadDesembolso><tipoCliente>

    Ejemplos:
      |Cedula|Credito|oficinaAsesor|nombresApellidos|fechaNacimiento|celular|Correo|actividad|pagaduria|Contacto|montoSolicitado|Tasa|Plazo|DiasHabilesIntereses|descNomina|descLey|Ingresos|VlrCompraSaneamiento|lineaCredito|rutaPDF|estadoActual|page|codigo|primerNombre|segundoNombre|primerApellido|segundoApellido|NombreCredito|fechaExpedicion|genero|estrado|tipoVivienda|claseVivienda|posicionHogar|nivelEscolaridad|cuotaHipotecaria|tipoDocNomina|otrosIngresos|modalidadDesembolso|tipoCliente|paisNacimiento|lugarDeNacimiento|nacionalidad|estadoCivil|profesion|departamento|ciudad|direccionResidencia|mesesResidencia|numeroHijos|personasACargo|tipoPension|codigoProgramaNomina|fechaIngreso|fechaTerminacion|nitAfiliacion|tipoDocumento|cargo|nombreBeneficario|documentoBeneficiario|celularBeneficiario|monedaExtranjera|tipoTransanccion|productoBancario|banco|numProducto|tipoProducto|pais|ciudad|monto|moneda|funcionarioPublico|recursosPublicos|expuestoPoliticamente|fechaExpuesto|Mes|fecha|AnnoAfetacion|TipoDesen|fechaActual|Banco|NumRadicadoCredito|
     ##@externaldata@./src/test/resources/data/AutomationDataRetanqueo.xlsx@RetanqueoDigiCredito
      | "10092369" | "55857" | "Soacha"      | "JAIRO MENDOZA DIAZ" | "19/10/1952"    | "3183903022" | "aalvarez@excelcredit.co" | "Pensionado" | "P.A COLPENSIONES" | "Entidad donde trabaja" | "20000000" | "1.70" | "60"  | "100"                | "260000"   | "100000" | "5500000" | "300000"             | "Retanqueo compra de cartera" | "src/test/resources/Data/PDFPRUEBA.pdf" | "Pendientes por Radicar" | ""   | "12345" | "JAIRO"      | ""            | "MENDOZA"      | "DIAZ"          | "JAIRO"       | "18/01/1974"    | "F"    | "Estrato 1" | "Arriendo"   | "Casa"        | "Jefe de hogar" | "Universitario"  | "100000"         | "Desprendible de nómina" | "30000000"    | "Pago masivo (efectivo)" | "AAA"       | "colombia"     | "colombia"        | "colombiano" | "Soltera/o" | "ingeniero" | "Antioquia"            | "Abejorral"      | "Cra 14 No. 93a - 30" | "24"            | "2"         | "0"            | "pension"   | "123456"             | "01/01/2015" | "30/12/2022"     | "123456"      | "Certificación laboral" | "CEO" | "Luis Perez Ramirez" | "1234567890"          | "3183903022"        | "No"             | "Importaciones"  | "No"             | "Santander" | "966855"    | "Inversiones en oro" | "Alemania" | "Berlin" | "8500" | "Euros" | "No"               | "No"             | "No"                  | "12/12/2008"  | "Febrero" | "20/07/1963" | "2022"        | "Efectivo" | "16/02/2022" | "Bancolombia Remanentes - 60237038927 - REMANENTE" | null               |

  @datosSolicitud
  Esquema del escenario: Diligenciamiento formulario Datos Solicitud
    Cuando busca el credito para retomar el estado actual <Cedula><estadoActual><page>
    Y registra los datos adicionales del cliente en Pagina 1 <paisNacimiento><lugarDeNacimiento><nacionalidad><estadoCivil><profesion>
    Y registra los datos adicionales del cliente en Pagina 2 <departamento><ciudad><direccionResidencia><mesesResidencia><numeroHijos><personasACargo><departamento><ciudad>
    #Y registra los datos adicionales del cliente en Pagina 3
    Y registra los datos adicionales del cliente en Pagina 4 <tipoPension><codigoProgramaNomina><fechaIngreso><fechaTerminacion><nitAfiliacion><tipoDocumento><rutaPDF><cargo>

    Ejemplos:
      |Cedula|Credito|oficinaAsesor|nombresApellidos|fechaNacimiento|celular|Correo|actividad|pagaduria|Contacto|montoSolicitado|Tasa|Plazo|DiasHabilesIntereses|descNomina|descLey|Ingresos|VlrCompraSaneamiento|lineaCredito|rutaPDF|estadoActual|page|codigo|primerNombre|segundoNombre|primerApellido|segundoApellido|NombreCredito|fechaExpedicion|genero|estrado|tipoVivienda|claseVivienda|posicionHogar|nivelEscolaridad|cuotaHipotecaria|tipoDocNomina|otrosIngresos|modalidadDesembolso|tipoCliente|paisNacimiento|lugarDeNacimiento|nacionalidad|estadoCivil|profesion|departamento|ciudad|direccionResidencia|mesesResidencia|numeroHijos|personasACargo|tipoPension|codigoProgramaNomina|fechaIngreso|fechaTerminacion|nitAfiliacion|tipoDocumento|cargo|nombreBeneficario|documentoBeneficiario|celularBeneficiario|monedaExtranjera|tipoTransanccion|productoBancario|banco|numProducto|tipoProducto|pais|ciudad|monto|moneda|funcionarioPublico|recursosPublicos|expuestoPoliticamente|fechaExpuesto|Mes|fecha|AnnoAfetacion|TipoDesen|fechaActual|Banco|NumRadicadoCredito|
     ##@externaldata@./src/test/resources/data/AutomationDataRetanqueo.xlsx@RetanqueoDigiCredito
      | "10092369" | "55857" | "Soacha"      | "JAIRO MENDOZA DIAZ" | "19/10/1952"    | "3183903022" | "aalvarez@excelcredit.co" | "Pensionado" | "P.A COLPENSIONES" | "Entidad donde trabaja" | "20000000" | "1.70" | "60"  | "100"                | "260000"   | "100000" | "5500000" | "300000"             | "Retanqueo compra de cartera" | "src/test/resources/Data/PDFPRUEBA.pdf" | "Pendientes por Radicar" | ""   | "12345" | "JAIRO"      | ""            | "MENDOZA"      | "DIAZ"          | "JAIRO"       | "18/01/1974"    | "F"    | "Estrato 1" | "Arriendo"   | "Casa"        | "Jefe de hogar" | "Universitario"  | "100000"         | "Desprendible de nómina" | "30000000"    | "Pago masivo (efectivo)" | "AAA"       | "colombia"     | "colombia"        | "colombiano" | "Soltera/o" | "ingeniero" | "Antioquia"            | "Abejorral"      | "Cra 14 No. 93a - 30" | "24"            | "2"         | "0"            | "pension"   | "123456"             | "01/01/2015" | "30/12/2022"     | "123456"      | "Certificación laboral" | "CEO" | "Luis Perez Ramirez" | "1234567890"          | "3183903022"        | "No"             | "Importaciones"  | "No"             | "Santander" | "966855"    | "Inversiones en oro" | "Alemania" | "Berlin" | "8500" | "Euros" | "No"               | "No"             | "No"                  | "12/12/2008"  | "Febrero" | "20/07/1963" | "2022"        | "Efectivo" | "16/02/2022" | "Bancolombia Remanentes - 60237038927 - REMANENTE" | null               |

  @datosSolicitudCredito
  Esquema del escenario: Diligenciamiento formulario Datos Solicitud Credito
    Cuando busca el credito para retomar el estado actual <Cedula><estadoActual><page>
    Entonces se registran los datos para el credito Retanqueo <Ingresos><descNomina><descLey><lineaCredito><Credito>
    Y se crean los tipos de cartera o saneamiento a recoger con la linea de <lineaDeCredito>
      | Contador | Entidad             | Monto  | VlrCuota | FechaVencimiento | NumObligacion |
      | 1        | ABOGADAS Y ASESORES | 100000 | 70000    | 28/02/2022       | 21236         |
      | 2        | ABOGADAS Y ASESORES | 100000 | 70000    | 28/02/2022       | 21236         |
      | 3        | ABOGADAS Y ASESORES | 100000 | 70000    | 28/02/2022       | 21236         |
    Y diligencia los datos calculo credito <montoSolicitado><Tasa><Plazo><DiasHabilesIntereses>
    Y se validan los datos del simulador datos solicitud <Tasa><Plazo><Ingresos><descLey><descNomina><pagaduria><DiasHabilesIntereses><Credito><VlrCompraSaneamiento><lineaCredito>
    Ejemplos:
      |Cedula|Credito|oficinaAsesor|nombresApellidos|fechaNacimiento|celular|Correo|actividad|pagaduria|Contacto|montoSolicitado|Tasa|Plazo|DiasHabilesIntereses|descNomina|descLey|Ingresos|VlrCompraSaneamiento|lineaCredito|rutaPDF|estadoActual|page|codigo|primerNombre|segundoNombre|primerApellido|segundoApellido|NombreCredito|fechaExpedicion|genero|estrado|tipoVivienda|claseVivienda|posicionHogar|nivelEscolaridad|cuotaHipotecaria|tipoDocNomina|otrosIngresos|modalidadDesembolso|tipoCliente|paisNacimiento|lugarDeNacimiento|nacionalidad|estadoCivil|profesion|departamento|ciudad|direccionResidencia|mesesResidencia|numeroHijos|personasACargo|tipoPension|codigoProgramaNomina|fechaIngreso|fechaTerminacion|nitAfiliacion|tipoDocumento|cargo|nombreBeneficario|documentoBeneficiario|celularBeneficiario|monedaExtranjera|tipoTransanccion|productoBancario|banco|numProducto|tipoProducto|pais|ciudad|monto|moneda|funcionarioPublico|recursosPublicos|expuestoPoliticamente|fechaExpuesto|Mes|fecha|AnnoAfetacion|TipoDesen|fechaActual|Banco|NumRadicadoCredito|
     ##@externaldata@./src/test/resources/data/AutomationDataRetanqueo.xlsx@RetanqueoDigiCredito
      | "10092369" | "55857" | "Soacha"      | "JAIRO MENDOZA DIAZ" | "19/10/1952"    | "3183903022" | "aalvarez@excelcredit.co" | "Pensionado" | "P.A COLPENSIONES" | "Entidad donde trabaja" | "20000000" | "1.70" | "60"  | "100"                | "260000"   | "100000" | "5500000" | "300000"             | "Retanqueo compra de cartera" | "src/test/resources/Data/PDFPRUEBA.pdf" | "Pendientes por Radicar" | ""   | "12345" | "JAIRO"      | ""            | "MENDOZA"      | "DIAZ"          | "JAIRO"       | "18/01/1974"    | "F"    | "Estrato 1" | "Arriendo"   | "Casa"        | "Jefe de hogar" | "Universitario"  | "100000"         | "Desprendible de nómina" | "30000000"    | "Pago masivo (efectivo)" | "AAA"       | "colombia"     | "colombia"        | "colombiano" | "Soltera/o" | "ingeniero" | "Antioquia"            | "Abejorral"      | "Cra 14 No. 93a - 30" | "24"            | "2"         | "0"            | "pension"   | "123456"             | "01/01/2015" | "30/12/2022"     | "123456"      | "Certificación laboral" | "CEO" | "Luis Perez Ramirez" | "1234567890"          | "3183903022"        | "No"             | "Importaciones"  | "No"             | "Santander" | "966855"    | "Inversiones en oro" | "Alemania" | "Berlin" | "8500" | "Euros" | "No"               | "No"             | "No"                  | "12/12/2008"  | "Febrero" | "20/07/1963" | "2022"        | "Efectivo" | "16/02/2022" | "Bancolombia Remanentes - 60237038927 - REMANENTE" | null               |


  @seguroAP
  Esquema del escenario: Etapa de seguro AP
    Cuando busca el credito para retomar el estado actual <numeroDocumento><estadoActual><page>
    Entonces Se visualizan los beneficios del seguro
    Y Se selecciona el vinculo del seguro y el plan <vinculo><plan><tomarSeguroAP>
    #Y Se llenan los campos de tomador del seguro <nombresApellidos><numeroDocumento><celular><correoElectronico><fechaNacimiento><departamento><ciudad><direccion>
    Y Se registran los beneficiarios <nombresSeguroAP><parentescoSeguroAP>

    Ejemplos:
      | nombresApellidos                 | numeroDocumento | fechaNacimiento | celular      | correoElectronico     |  estadoActual | page | vinculo        | plan     | nombresSeguroAP | parentescoSeguroAP | departamento | ciudad   | direccion         |tomarSeguroAP|
      | "RUBY ALEYDA RODRIGUEZ GONZALEZ" | "52912399"      | "06/09/1979"    | "3132739036" | "dabogadog@gmail.com" |  ""           | ""   | "Vinculado"    | "Plan 1" | "Juli Macias"   | "Prima"            | "Bogotá D.C" | "Bogota" | "calle 2d #22-52" |"Si"         |

  @referencias
  Esquema del escenario: Diligenciamiento de referencias personales y familiares
    Cuando busca el credito para retomar el estado actual <numeroDocumento><estadoActual><page>
    Y Se ingresa la informacion de las referencias personales <pNombreRefP><sNombreRefP><pApellidoRefP><sApellidoRefP><relacionRefP><celRefP><deptoRefP><ciudadRefP>
    Y Se ingresa la informacion de las referencias familiares <pNombreRefF><sNombreRefF><pApellidoRefF><sApellidoRefF><relacionRefF><celRefF><deptoRefF><ciudadRefF>
    Ejemplos:
      | numeroDocumento | estadoActual                 | page | pNombreRefP | sNombreRefP | pApellidoRefP | sApellidoRefP | relacionRefP | celRefP      | deptoRefP | ciudadRefP | pNombreRefF | sNombreRefF | pApellidoRefF | sApellidoRefF | relacionRefF | celRefF      | deptoRefF  | ciudadRefF |
      | "52912399"      | "En registro de referencias" | ""   | "maria"     | "camila"    | "lopez"       | "cardenas"    | "Amigo"      | "3204567894" | "Arauca"  | "Arauca"   | "juan"      | "david"     | "reyes"       | "sanchez"     | "Hijo"       | "3204047804" | "Amazonas" | "Leticia"  |


  @seguroVida
  Esquema del escenario: Registrar beneficiarios seguro de vida
    Cuando busca el credito para retomar el estado actual <Cedula><estadoActual><page>
    Entonces diligencia minimo tres beneficiaros para el seguro de vida <nombreBeneficario><documentoBeneficiario><celularBeneficiario><departamento><ciudad>

    Ejemplos:
      |Cedula|Credito|oficinaAsesor|nombresApellidos|fechaNacimiento|celular|Correo|actividad|pagaduria|Contacto|montoSolicitado|Tasa|Plazo|DiasHabilesIntereses|descNomina|descLey|Ingresos|VlrCompraSaneamiento|lineaCredito|rutaPDF|estadoActual|page|codigo|primerNombre|segundoNombre|primerApellido|segundoApellido|NombreCredito|fechaExpedicion|genero|estrado|tipoVivienda|claseVivienda|posicionHogar|nivelEscolaridad|cuotaHipotecaria|tipoDocNomina|otrosIngresos|modalidadDesembolso|tipoCliente|paisNacimiento|lugarDeNacimiento|nacionalidad|estadoCivil|profesion|departamento|ciudad|direccionResidencia|mesesResidencia|numeroHijos|personasACargo|tipoPension|codigoProgramaNomina|fechaIngreso|fechaTerminacion|nitAfiliacion|tipoDocumento|cargo|nombreBeneficario|documentoBeneficiario|celularBeneficiario|monedaExtranjera|tipoTransanccion|productoBancario|banco|numProducto|tipoProducto|pais|ciudad|monto|moneda|funcionarioPublico|recursosPublicos|expuestoPoliticamente|fechaExpuesto|Mes|fecha|AnnoAfetacion|TipoDesen|fechaActual|Banco|NumRadicadoCredito|
     ##@externaldata@./src/test/resources/data/AutomationDataRetanqueo.xlsx@RetanqueoDigiCredito
      | "10092369" | "55857" | "Soacha"      | "JAIRO MENDOZA DIAZ" | "19/10/1952"    | "3183903022" | "aalvarez@excelcredit.co" | "Pensionado" | "P.A COLPENSIONES" | "Entidad donde trabaja" | "20000000" | "1.70" | "60"  | "100"                | "260000"   | "100000" | "5500000" | "300000"             | "Retanqueo compra de cartera" | "src/test/resources/Data/PDFPRUEBA.pdf" | "Pendientes por Radicar" | ""   | "12345" | "JAIRO"      | ""            | "MENDOZA"      | "DIAZ"          | "JAIRO"       | "18/01/1974"    | "F"    | "Estrato 1" | "Arriendo"   | "Casa"        | "Jefe de hogar" | "Universitario"  | "100000"         | "Desprendible de nómina" | "30000000"    | "Pago masivo (efectivo)" | "AAA"       | "colombia"     | "colombia"        | "colombiano" | "Soltera/o" | "ingeniero" | "Antioquia"            | "Abejorral"      | "Cra 14 No. 93a - 30" | "24"            | "2"         | "0"            | "pension"   | "123456"             | "01/01/2015" | "30/12/2022"     | "123456"      | "Certificación laboral" | "CEO" | "Luis Perez Ramirez" | "1234567890"          | "3183903022"        | "No"             | "Importaciones"  | "No"             | "Santander" | "966855"    | "Inversiones en oro" | "Alemania" | "Berlin" | "8500" | "Euros" | "No"               | "No"             | "No"                  | "12/12/2008"  | "Febrero" | "20/07/1963" | "2022"        | "Efectivo" | "16/02/2022" | "Bancolombia Remanentes - 60237038927 - REMANENTE" | null               |

  @OperInternacionalesPEPS
  Esquema del escenario: Registrar operaciones internacionales y PEPS
    Cuando busca el credito para retomar el estado actual <Cedula><estadoActual><page>
    Y llena el formulario de operaciones internacionales <monedaExtranjera><tipoTransanccion><productoBancario><banco><numProducto><tipoProducto><pais><ciudad><monto><moneda>
    Y llena el formulario de persona expuesta politicamente <funcionarioPublico><recursosPublicos><expuestoPoliticamente><fechaExpuesto>
    Ejemplos:
      |Cedula|Credito|oficinaAsesor|nombresApellidos|fechaNacimiento|celular|Correo|actividad|pagaduria|Contacto|montoSolicitado|Tasa|Plazo|DiasHabilesIntereses|descNomina|descLey|Ingresos|VlrCompraSaneamiento|lineaCredito|rutaPDF|estadoActual|page|codigo|primerNombre|segundoNombre|primerApellido|segundoApellido|NombreCredito|fechaExpedicion|genero|estrado|tipoVivienda|claseVivienda|posicionHogar|nivelEscolaridad|cuotaHipotecaria|tipoDocNomina|otrosIngresos|modalidadDesembolso|tipoCliente|paisNacimiento|lugarDeNacimiento|nacionalidad|estadoCivil|profesion|departamento|ciudad|direccionResidencia|mesesResidencia|numeroHijos|personasACargo|tipoPension|codigoProgramaNomina|fechaIngreso|fechaTerminacion|nitAfiliacion|tipoDocumento|cargo|nombreBeneficario|documentoBeneficiario|celularBeneficiario|monedaExtranjera|tipoTransanccion|productoBancario|banco|numProducto|tipoProducto|pais|ciudad|monto|moneda|funcionarioPublico|recursosPublicos|expuestoPoliticamente|fechaExpuesto|Mes|fecha|AnnoAfetacion|TipoDesen|fechaActual|Banco|NumRadicadoCredito|
     ##@externaldata@./src/test/resources/data/AutomationDataRetanqueo.xlsx@RetanqueoDigiCredito
      | "10092369" | "55857" | "Soacha"      | "JAIRO MENDOZA DIAZ" | "19/10/1952"    | "3183903022" | "aalvarez@excelcredit.co" | "Pensionado" | "P.A COLPENSIONES" | "Entidad donde trabaja" | "20000000" | "1.70" | "60"  | "100"                | "260000"   | "100000" | "5500000" | "300000"             | "Retanqueo compra de cartera" | "src/test/resources/Data/PDFPRUEBA.pdf" | "Pendientes por Radicar" | ""   | "12345" | "JAIRO"      | ""            | "MENDOZA"      | "DIAZ"          | "JAIRO"       | "18/01/1974"    | "F"    | "Estrato 1" | "Arriendo"   | "Casa"        | "Jefe de hogar" | "Universitario"  | "100000"         | "Desprendible de nómina" | "30000000"    | "Pago masivo (efectivo)" | "AAA"       | "colombia"     | "colombia"        | "colombiano" | "Soltera/o" | "ingeniero" | "Antioquia"            | "Abejorral"      | "Cra 14 No. 93a - 30" | "24"            | "2"         | "0"            | "pension"   | "123456"             | "01/01/2015" | "30/12/2022"     | "123456"      | "Certificación laboral" | "CEO" | "Luis Perez Ramirez" | "1234567890"          | "3183903022"        | "No"             | "Importaciones"  | "No"             | "Santander" | "966855"    | "Inversiones en oro" | "Alemania" | "Berlin" | "8500" | "Euros" | "No"               | "No"             | "No"                  | "12/12/2008"  | "Febrero" | "20/07/1963" | "2022"        | "Efectivo" | "16/02/2022" | "Bancolombia Remanentes - 60237038927 - REMANENTE" | null               |


  @firmaDocumentos
  Esquema del escenario: Realiza la firma final de documentos
    Cuando busca el credito para retomar el estado actual <Cedula><estadoActual><page>
    Y consulta el codigo OTP <Cedula>
    Y descarga los documentos a firmar
    Entonces diligencia el tipo de documento y adjunta el archivo <rutaPdf>

    Ejemplos:
      |Cedula|Credito|oficinaAsesor|nombresApellidos|fechaNacimiento|celular|Correo|actividad|pagaduria|Contacto|montoSolicitado|Tasa|Plazo|DiasHabilesIntereses|descNomina|descLey|Ingresos|VlrCompraSaneamiento|lineaCredito|rutaPDF|estadoActual|page|codigo|primerNombre|segundoNombre|primerApellido|segundoApellido|NombreCredito|fechaExpedicion|genero|estrado|tipoVivienda|claseVivienda|posicionHogar|nivelEscolaridad|cuotaHipotecaria|tipoDocNomina|otrosIngresos|modalidadDesembolso|tipoCliente|paisNacimiento|lugarDeNacimiento|nacionalidad|estadoCivil|profesion|departamento|ciudad|direccionResidencia|mesesResidencia|numeroHijos|personasACargo|tipoPension|codigoProgramaNomina|fechaIngreso|fechaTerminacion|nitAfiliacion|tipoDocumento|cargo|nombreBeneficario|documentoBeneficiario|celularBeneficiario|monedaExtranjera|tipoTransanccion|productoBancario|banco|numProducto|tipoProducto|pais|ciudad|monto|moneda|funcionarioPublico|recursosPublicos|expuestoPoliticamente|fechaExpuesto|Mes|fecha|AnnoAfetacion|TipoDesen|fechaActual|Banco|NumRadicadoCredito|
     ##@externaldata@./src/test/resources/data/AutomationDataRetanqueo.xlsx@RetanqueoDigiCredito
      | "10092369" | "55857" | "Soacha"      | "JAIRO MENDOZA DIAZ" | "19/10/1952"    | "3183903022" | "aalvarez@excelcredit.co" | "Pensionado" | "P.A COLPENSIONES" | "Entidad donde trabaja" | "20000000" | "1.70" | "60"  | "100"                | "260000"   | "100000" | "5500000" | "300000"             | "Retanqueo compra de cartera" | "src/test/resources/Data/PDFPRUEBA.pdf" | "Pendientes por Radicar" | ""   | "12345" | "JAIRO"      | ""            | "MENDOZA"      | "DIAZ"          | "JAIRO"       | "18/01/1974"    | "F"    | "Estrato 1" | "Arriendo"   | "Casa"        | "Jefe de hogar" | "Universitario"  | "100000"         | "Desprendible de nómina" | "30000000"    | "Pago masivo (efectivo)" | "AAA"       | "colombia"     | "colombia"        | "colombiano" | "Soltera/o" | "ingeniero" | "Antioquia"            | "Abejorral"      | "Cra 14 No. 93a - 30" | "24"            | "2"         | "0"            | "pension"   | "123456"             | "01/01/2015" | "30/12/2022"     | "123456"      | "Certificación laboral" | "CEO" | "Luis Perez Ramirez" | "1234567890"          | "3183903022"        | "No"             | "Importaciones"  | "No"             | "Santander" | "966855"    | "Inversiones en oro" | "Alemania" | "Berlin" | "8500" | "Euros" | "No"               | "No"             | "No"                  | "12/12/2008"  | "Febrero" | "20/07/1963" | "2022"        | "Efectivo" | "16/02/2022" | "Bancolombia Remanentes - 60237038927 - REMANENTE" | null               |

