#language: es

Característica: Simulador Digicredito

  Antecedentes:
    Cuando se asigna el usuario
    Y ingresa su usuario 88776655 y contrasena 4112935


  @Simulador
  Esquema del escenario:  Simulador Inicial
    Dado la actualizacion del usuario autorizado para la <Cedula>
    Entonces el usuario diligencias los campos del formulario <oficinaAsesor><nombresApellidos><Cedula><fechaNacimiento><Celular><Correo><Actividad><Pagaduria><Contacto>
    Y ingresa la informacion de los valores credito a solicitar <montoSolicitado><Tasa><Plazo><DiasHabilesIntereses>
    Y diligencia los datos financieros <Ingresos><descLey><descNomina><lineaCredito><Credito><vlrCompasSaneamientos><Pagaduria>
    Y se validan los campos del simulador <Tasa><Plazo><Ingresos><descLey><descNomina><Pagaduria><DiasHabilesIntereses><Credito><vlrCompasSaneamientos><lineaCredito><Cedula>
    Y se inicia la solicitud del credito
    Entonces El usuario carga los archivos imagen de la cedula del cliente <rutaPDF>
    Y realiza el registro del cliente paso 2 de 4 <Cedula><primerNombre><segundoNombre><primerApellido><segundoApellido><fechaNacimiento><fechaExpedicion><departamento><ciudad><genero>
    Y se llenan los datos adicionales <departamento><ciudad>
    Entonces se realiza el proceso de Prospeccion del cliente <Cedula>
    Cuando busca el credito para retomar el estado actual <Cedula><estadoActual><page>
    Y recorre las paginas de la consulta de propeccion
    Y valida el cambio de estado del credito <Cedula> con estado "EN_PROCESO_CALCULO_ENDEUDAMIENTO"

    Ejemplos:
      | Pagaduria   | Cedula       | Tasa   | Plazo | montoSolicitado | DiasHabilesIntereses | Ingresos  | descLey  | descNomina | Mes         | fechaDesembolso | primerNombre | segundoNombre | primerApellido | segundoApellido | fechaActual   | oficinaAsesor | Actividad    | TotalActivos | vlrCompasSaneamientos | TipoContrato | FechaIngreso | Correo                    | Celular      | departamento   | ciudad     | rutaPDF                                 | DestinoCredito     | genero | EstadoCivil | direccionResidencia | TipoVivienda | PapellidoReferencia | PnombreReferencia | TelefonoResidencia | TelefonoTrabajo | Codigo | AnoAnalisis | TipoDesen  | Banco                                  | AccountingSource   | AccountingName                                                          | FechaRegistro | Cartera1 | Saneamiento2 | Credito | nombresApellidos       | fechaNacimiento | Contacto                | lineaCredito      | estadoActual | page | codigo  | fechaExpedicion | estrado     | claseVivienda | posicionHogar   | nivelEscolaridad | cuotaHipotecaria | tipoDocNomina            | otrosIngresos | modalidadDesembolso      | tipoCliente | paisNacimiento | lugarDeNacimiento | nacionalidad | profesion   | mesesResidencia | numeroHijos | personasACargo | tipoPension | codigoProgramaNomina | fechaTerminacion | nitAfiliacion | tipoDocumento           | cargo | nombreBeneficario    | documentoBeneficiario | celularBeneficiario | monedaExtranjera | tipoTransanccion | productoBancario | banco       | numProducto | tipoProducto         | pais       | ciudadExt | monto  | moneda  | funcionarioPublico | recursosPublicos | expuestoPoliticamente | fechaExpuesto | Mes       | fecha        | AnnoAfetacion | fechaActual  | Banco                                              | vinculo     | plan     | tomarSeguroAP | nombresSeguroAP | parentescoSeguroAP | pNombreRefP | sNombreRefP | pApellidoRefP | sApellidoRefP | relacionRefP | celRefP      | pNombreRefF | sNombreRefF | pApellidoRefF | sApellidoRefF | relacionRefF | celRefF      | decisionExcepcion | NumRadicacion | tipocontratoAbacus         |
     ##@externaldata@./src/test/resources/data/AutomationData.xlsx@dataDigicredito
   |"COLFONDOS"   |"1017171608"   |"1.70"   |"50"   |"7500000"   |"50"   |"8500000"   |"250000"   |"300000"   |"Noviembre"   |"05/10/2021"   |"GERSON"   |""   |"ALONZO"   |"VARGAS"   |"25/Nov/2021"   |"Soacha"   |"Pensionado"   |"20500000"   |"0"   |"Jubilados"   |"10/03/2000"   |"thainer.perez@gmail.com"     |"3133421083"   |"Cundinamarca"   |"Anapoima"   |"src/test/resources/Data/PDFPRUEBA.pdf"   |"Educacion propia"   |"M"   |"Soltera/o"   |"Calle 2d #22-52"   |"Arriendo"   |"perez"   |"alejandro"   |"7210273"   |"9007146"   |"3112"   |"2021"   |"Efectivo"   |"Remanentes - 60237038927 - REMANENTE"   |"'ACRED','EGRESO'"    |"upper('Desembolso egreso'), upper('Desembolso activación de crédito')"   |29/10/2021   |"300000"   |"0"   |"86313"   |"GERSON ALONZO VARGAS"   |"15/02/1956"   |"Entidad donde trabaja"   |"Libre inversion"   |""   |""   |"12345"   |"06/08/1976"    |"Estrato 1"    |"Casa"   |"Jefe de hogar"   | "Universitario"    |"100000"   |"Desprendible de nómina"    |"5000000"   |"Pago masivo (efectivo)"    |"AAA"   |"colombia"   |"colombia"   |"colombiano"   |"ingeniero"    |"24"   |"2"      |"0"   |"pension"   |"123456"     |"30/12/2022"   |"123456"   |"Certificación laboral"   |"CEO"   |"Luis Perez Ramirez"   |"1234567890"   |"3183903022"   |"No"   |"Importaciones"   |"No"   |"Santander"   |"966855"   |"Inversiones en oro"    |"Alemania"   |"Berlin"   |"8500"   |"Euros"   |"No"   |"No"   |"No"   |"12/12/2008"   |"Febrero"   |"20/07/1963"   |"2022"   |"16/02/2022"   |"Bancolombia Remanentes - 60237038927 - REMANENTE"    |"Vinculado"   |"Plan 1"   |"No"   |"Juli Macias"   |"Prima"   |"maria"   |"camila"   |"lopez"   |"cardenas"   |"Amigo"   |"3204567894"   |"juan"   |"david"   |"reyes"   |"sanchez"   |"Hijo"   |"3204047804"   |"No"   |"92840"   |"Pensionado por Invalidez"|

  @endeudamientoGlobal
  Esquema del escenario: Diligencia los datos de endeudamiento global
    Cuando busca el credito para retomar el estado actual <Cedula><estadoActual><page>
    Y registra la informacion basica solicitante <Codigo><estrado><TipoVivienda><claseVivienda><posicionHogar><nivelEscolaridad>
    Y registra la informacion financiera <descLey><descNomina>
    Entonces finaliza registrando la informacion a centrales <cuotaHipotecaria><tipoDocNomina><rutaPDF><otrosIngresos>
    Y valida el cambio de estado del credito <Cedula> con estado "EN_REGISTRO_DATOS_ADICIONALES_CLIENTE"

    Ejemplos:
      | Pagaduria   | Cedula       | Tasa   | Plazo | montoSolicitado | DiasHabilesIntereses | Ingresos  | descLey  | descNomina | Mes         | fechaDesembolso | primerNombre | segundoNombre | primerApellido | segundoApellido | fechaActual   | oficinaAsesor | Actividad    | TotalActivos | vlrCompasSaneamientos | TipoContrato | FechaIngreso | Correo                    | Celular      | departamento   | ciudad     | rutaPDF                                 | DestinoCredito     | genero | EstadoCivil | direccionResidencia | TipoVivienda | PapellidoReferencia | PnombreReferencia | TelefonoResidencia | TelefonoTrabajo | Codigo | AnoAnalisis | TipoDesen  | Banco                                  | AccountingSource   | AccountingName                                                          | FechaRegistro | Cartera1 | Saneamiento2 | Credito | nombresApellidos       | fechaNacimiento | Contacto                | lineaCredito      | estadoActual | page | codigo  | fechaExpedicion | estrado     | claseVivienda | posicionHogar   | nivelEscolaridad | cuotaHipotecaria | tipoDocNomina            | otrosIngresos | modalidadDesembolso      | tipoCliente | paisNacimiento | lugarDeNacimiento | nacionalidad | profesion   | mesesResidencia | numeroHijos | personasACargo | tipoPension | codigoProgramaNomina | fechaTerminacion | nitAfiliacion | tipoDocumento           | cargo | nombreBeneficario    | documentoBeneficiario | celularBeneficiario | monedaExtranjera | tipoTransanccion | productoBancario | banco       | numProducto | tipoProducto         | pais       | ciudadExt | monto  | moneda  | funcionarioPublico | recursosPublicos | expuestoPoliticamente | fechaExpuesto | Mes       | fecha        | AnnoAfetacion | fechaActual  | Banco                                              | vinculo     | plan     | tomarSeguroAP | nombresSeguroAP | parentescoSeguroAP | pNombreRefP | sNombreRefP | pApellidoRefP | sApellidoRefP | relacionRefP | celRefP      | pNombreRefF | sNombreRefF | pApellidoRefF | sApellidoRefF | relacionRefF | celRefF      | decisionExcepcion | NumRadicacion | tipocontratoAbacus         |
     ##@externaldata@./src/test/resources/data/AutomationData.xlsx@dataDigicredito
   |"COLFONDOS"   |"1017171608"   |"1.70"   |"50"   |"7500000"   |"50"   |"8500000"   |"250000"   |"300000"   |"Noviembre"   |"05/10/2021"   |"GERSON"   |""   |"ALONZO"   |"VARGAS"   |"25/Nov/2021"   |"Soacha"   |"Pensionado"   |"20500000"   |"0"   |"Jubilados"   |"10/03/2000"   |"thainer.perez@gmail.com"     |"3133421083"   |"Cundinamarca"   |"Anapoima"   |"src/test/resources/Data/PDFPRUEBA.pdf"   |"Educacion propia"   |"M"   |"Soltera/o"   |"Calle 2d #22-52"   |"Arriendo"   |"perez"   |"alejandro"   |"7210273"   |"9007146"   |"3112"   |"2021"   |"Efectivo"   |"Remanentes - 60237038927 - REMANENTE"   |"'ACRED','EGRESO'"    |"upper('Desembolso egreso'), upper('Desembolso activación de crédito')"   |29/10/2021   |"300000"   |"0"   |"86313"   |"GERSON ALONZO VARGAS"   |"15/02/1956"   |"Entidad donde trabaja"   |"Libre inversion"   |""   |""   |"12345"   |"06/08/1976"    |"Estrato 1"    |"Casa"   |"Jefe de hogar"   | "Universitario"    |"100000"   |"Desprendible de nómina"    |"5000000"   |"Pago masivo (efectivo)"    |"AAA"   |"colombia"   |"colombia"   |"colombiano"   |"ingeniero"    |"24"   |"2"      |"0"   |"pension"   |"123456"     |"30/12/2022"   |"123456"   |"Certificación laboral"   |"CEO"   |"Luis Perez Ramirez"   |"1234567890"   |"3183903022"   |"No"   |"Importaciones"   |"No"   |"Santander"   |"966855"   |"Inversiones en oro"    |"Alemania"   |"Berlin"   |"8500"   |"Euros"   |"No"   |"No"   |"No"   |"12/12/2008"   |"Febrero"   |"20/07/1963"   |"2022"   |"16/02/2022"   |"Bancolombia Remanentes - 60237038927 - REMANENTE"    |"Vinculado"   |"Plan 1"   |"No"   |"Juli Macias"   |"Prima"   |"maria"   |"camila"   |"lopez"   |"cardenas"   |"Amigo"   |"3204567894"   |"juan"   |"david"   |"reyes"   |"sanchez"   |"Hijo"   |"3204047804"   |"No"   |"92840"   |"Pensionado por Invalidez"|

  @desembolso
  Esquema del escenario: Diligenciamiento del desembolso
    Cuando busca el credito para retomar el estado actual <Cedula><estadoActual><page>
    Y se selecciona la modalidad de desembolso y tipo de cliente <modalidadDesembolso><tipoCliente>
    #Y valida el cambio de estado del credito <Cedula> con estado "EN_REGISTRO_DATOS_ADICIONALES_CLIENTE"
    Ejemplos:
      | Pagaduria   | Cedula       | Tasa   | Plazo | montoSolicitado | DiasHabilesIntereses | Ingresos  | descLey  | descNomina | Mes         | fechaDesembolso | primerNombre | segundoNombre | primerApellido | segundoApellido | fechaActual   | oficinaAsesor | Actividad    | TotalActivos | vlrCompasSaneamientos | TipoContrato | FechaIngreso | Correo                    | Celular      | departamento   | ciudad     | rutaPDF                                 | DestinoCredito     | genero | EstadoCivil | direccionResidencia | TipoVivienda | PapellidoReferencia | PnombreReferencia | TelefonoResidencia | TelefonoTrabajo | Codigo | AnoAnalisis | TipoDesen  | Banco                                  | AccountingSource   | AccountingName                                                          | FechaRegistro | Cartera1 | Saneamiento2 | Credito | nombresApellidos       | fechaNacimiento | Contacto                | lineaCredito      | estadoActual | page | codigo  | fechaExpedicion | estrado     | claseVivienda | posicionHogar   | nivelEscolaridad | cuotaHipotecaria | tipoDocNomina            | otrosIngresos | modalidadDesembolso      | tipoCliente | paisNacimiento | lugarDeNacimiento | nacionalidad | profesion   | mesesResidencia | numeroHijos | personasACargo | tipoPension | codigoProgramaNomina | fechaTerminacion | nitAfiliacion | tipoDocumento           | cargo | nombreBeneficario    | documentoBeneficiario | celularBeneficiario | monedaExtranjera | tipoTransanccion | productoBancario | banco       | numProducto | tipoProducto         | pais       | ciudadExt | monto  | moneda  | funcionarioPublico | recursosPublicos | expuestoPoliticamente | fechaExpuesto | Mes       | fecha        | AnnoAfetacion | fechaActual  | Banco                                              | vinculo     | plan     | tomarSeguroAP | nombresSeguroAP | parentescoSeguroAP | pNombreRefP | sNombreRefP | pApellidoRefP | sApellidoRefP | relacionRefP | celRefP      | pNombreRefF | sNombreRefF | pApellidoRefF | sApellidoRefF | relacionRefF | celRefF      | decisionExcepcion | NumRadicacion | tipocontratoAbacus         |
     ##@externaldata@./src/test/resources/data/AutomationData.xlsx@dataDigicredito
   |"COLFONDOS"   |"1017171608"   |"1.70"   |"50"   |"7500000"   |"50"   |"8500000"   |"250000"   |"300000"   |"Noviembre"   |"05/10/2021"   |"GERSON"   |""   |"ALONZO"   |"VARGAS"   |"25/Nov/2021"   |"Soacha"   |"Pensionado"   |"20500000"   |"0"   |"Jubilados"   |"10/03/2000"   |"thainer.perez@gmail.com"     |"3133421083"   |"Cundinamarca"   |"Anapoima"   |"src/test/resources/Data/PDFPRUEBA.pdf"   |"Educacion propia"   |"M"   |"Soltera/o"   |"Calle 2d #22-52"   |"Arriendo"   |"perez"   |"alejandro"   |"7210273"   |"9007146"   |"3112"   |"2021"   |"Efectivo"   |"Remanentes - 60237038927 - REMANENTE"   |"'ACRED','EGRESO'"    |"upper('Desembolso egreso'), upper('Desembolso activación de crédito')"   |29/10/2021   |"300000"   |"0"   |"86313"   |"GERSON ALONZO VARGAS"   |"15/02/1956"   |"Entidad donde trabaja"   |"Libre inversion"   |""   |""   |"12345"   |"06/08/1976"    |"Estrato 1"    |"Casa"   |"Jefe de hogar"   | "Universitario"    |"100000"   |"Desprendible de nómina"    |"5000000"   |"Pago masivo (efectivo)"    |"AAA"   |"colombia"   |"colombia"   |"colombiano"   |"ingeniero"    |"24"   |"2"      |"0"   |"pension"   |"123456"     |"30/12/2022"   |"123456"   |"Certificación laboral"   |"CEO"   |"Luis Perez Ramirez"   |"1234567890"   |"3183903022"   |"No"   |"Importaciones"   |"No"   |"Santander"   |"966855"   |"Inversiones en oro"    |"Alemania"   |"Berlin"   |"8500"   |"Euros"   |"No"   |"No"   |"No"   |"12/12/2008"   |"Febrero"   |"20/07/1963"   |"2022"   |"16/02/2022"   |"Bancolombia Remanentes - 60237038927 - REMANENTE"    |"Vinculado"   |"Plan 1"   |"No"   |"Juli Macias"   |"Prima"   |"maria"   |"camila"   |"lopez"   |"cardenas"   |"Amigo"   |"3204567894"   |"juan"   |"david"   |"reyes"   |"sanchez"   |"Hijo"   |"3204047804"   |"No"   |"92840"   |"Pensionado por Invalidez"|

  @datosSolicitud
  Esquema del escenario: Diligenciamiento formulario Datos Solicitud
    Cuando busca el credito para retomar el estado actual <Cedula><estadoActual><page>
    Y registra los datos adicionales del cliente en Pagina 1 <paisNacimiento><lugarDeNacimiento><nacionalidad><EstadoCivil><profesion>
    Y registra los datos adicionales del cliente en Pagina 2 <departamento><ciudad><direccionResidencia><mesesResidencia><numeroHijos><personasACargo><departamento><ciudad>
    Y registra los datos adicionales del cliente en Pagina 4 <tipoPension><codigoProgramaNomina><FechaIngreso><fechaTerminacion><nitAfiliacion><tipoDocumento><rutaPDF><cargo>
    Y valida el cambio de estado del credito <Cedula> con estado "EN_SIMULACION_FINAL_ASESOR"

    Ejemplos:
      | Pagaduria   | Cedula       | Tasa   | Plazo | montoSolicitado | DiasHabilesIntereses | Ingresos  | descLey  | descNomina | Mes         | fechaDesembolso | primerNombre | segundoNombre | primerApellido | segundoApellido | fechaActual   | oficinaAsesor | Actividad    | TotalActivos | vlrCompasSaneamientos | TipoContrato | FechaIngreso | Correo                    | Celular      | departamento   | ciudad     | rutaPDF                                 | DestinoCredito     | genero | EstadoCivil | direccionResidencia | TipoVivienda | PapellidoReferencia | PnombreReferencia | TelefonoResidencia | TelefonoTrabajo | Codigo | AnoAnalisis | TipoDesen  | Banco                                  | AccountingSource   | AccountingName                                                          | FechaRegistro | Cartera1 | Saneamiento2 | Credito | nombresApellidos       | fechaNacimiento | Contacto                | lineaCredito      | estadoActual | page | codigo  | fechaExpedicion | estrado     | claseVivienda | posicionHogar   | nivelEscolaridad | cuotaHipotecaria | tipoDocNomina            | otrosIngresos | modalidadDesembolso      | tipoCliente | paisNacimiento | lugarDeNacimiento | nacionalidad | profesion   | mesesResidencia | numeroHijos | personasACargo | tipoPension | codigoProgramaNomina | fechaTerminacion | nitAfiliacion | tipoDocumento           | cargo | nombreBeneficario    | documentoBeneficiario | celularBeneficiario | monedaExtranjera | tipoTransanccion | productoBancario | banco       | numProducto | tipoProducto         | pais       | ciudadExt | monto  | moneda  | funcionarioPublico | recursosPublicos | expuestoPoliticamente | fechaExpuesto | Mes       | fecha        | AnnoAfetacion | fechaActual  | Banco                                              | vinculo     | plan     | tomarSeguroAP | nombresSeguroAP | parentescoSeguroAP | pNombreRefP | sNombreRefP | pApellidoRefP | sApellidoRefP | relacionRefP | celRefP      | pNombreRefF | sNombreRefF | pApellidoRefF | sApellidoRefF | relacionRefF | celRefF      | decisionExcepcion | NumRadicacion | tipocontratoAbacus         |
     ##@externaldata@./src/test/resources/data/AutomationData.xlsx@dataDigicredito
   |"COLFONDOS"   |"1017171608"   |"1.70"   |"50"   |"7500000"   |"50"   |"8500000"   |"250000"   |"300000"   |"Noviembre"   |"05/10/2021"   |"GERSON"   |""   |"ALONZO"   |"VARGAS"   |"25/Nov/2021"   |"Soacha"   |"Pensionado"   |"20500000"   |"0"   |"Jubilados"   |"10/03/2000"   |"thainer.perez@gmail.com"     |"3133421083"   |"Cundinamarca"   |"Anapoima"   |"src/test/resources/Data/PDFPRUEBA.pdf"   |"Educacion propia"   |"M"   |"Soltera/o"   |"Calle 2d #22-52"   |"Arriendo"   |"perez"   |"alejandro"   |"7210273"   |"9007146"   |"3112"   |"2021"   |"Efectivo"   |"Remanentes - 60237038927 - REMANENTE"   |"'ACRED','EGRESO'"    |"upper('Desembolso egreso'), upper('Desembolso activación de crédito')"   |29/10/2021   |"300000"   |"0"   |"86313"   |"GERSON ALONZO VARGAS"   |"15/02/1956"   |"Entidad donde trabaja"   |"Libre inversion"   |""   |""   |"12345"   |"06/08/1976"    |"Estrato 1"    |"Casa"   |"Jefe de hogar"   | "Universitario"    |"100000"   |"Desprendible de nómina"    |"5000000"   |"Pago masivo (efectivo)"    |"AAA"   |"colombia"   |"colombia"   |"colombiano"   |"ingeniero"    |"24"   |"2"      |"0"   |"pension"   |"123456"     |"30/12/2022"   |"123456"   |"Certificación laboral"   |"CEO"   |"Luis Perez Ramirez"   |"1234567890"   |"3183903022"   |"No"   |"Importaciones"   |"No"   |"Santander"   |"966855"   |"Inversiones en oro"    |"Alemania"   |"Berlin"   |"8500"   |"Euros"   |"No"   |"No"   |"No"   |"12/12/2008"   |"Febrero"   |"20/07/1963"   |"2022"   |"16/02/2022"   |"Bancolombia Remanentes - 60237038927 - REMANENTE"    |"Vinculado"   |"Plan 1"   |"No"   |"Juli Macias"   |"Prima"   |"maria"   |"camila"   |"lopez"   |"cardenas"   |"Amigo"   |"3204567894"   |"juan"   |"david"   |"reyes"   |"sanchez"   |"Hijo"   |"3204047804"   |"No"   |"92840"   |"Pensionado por Invalidez"|

  @datosSolicitudCredito
  Esquema del escenario: Diligenciamiento formulario Datos Solicitud Credito
    Cuando busca el credito para retomar el estado actual <Cedula><estadoActual><page>
    Entonces se registran los datos para el credito Retanqueo <Ingresos><descNomina><descLey><lineaCredito><Credito><Pagaduria>
    Y se crean los tipos de cartera o saneamiento a recoger con la linea de <lineaCredito>
      | Contador | Entidad             | Monto  | VlrCuota | FechaVencimiento | NumObligacion |
      | 1        | ABOGADAS Y ASESORES | 300000 | 70000    | 30/12/2021       | 21236         |
      | 2        | ABOGADAS Y ASESORES | 200000 | 70000    | 30/12/2021       | 21236         |
      | 3        | ABOGADAS Y ASESORES | 100000 | 70000    | 30/12/2021       | 21236         |
    Y diligencia los datos calculo credito <montoSolicitado><Tasa><Plazo><DiasHabilesIntereses>
    Y se validan los datos del simulador datos solicitud <Tasa><Plazo><Ingresos><descLey><descNomina><Pagaduria><DiasHabilesIntereses><Credito><vlrCompasSaneamientos><lineaCredito><Cedula>
    Y valida el cambio de estado del credito <Cedula> con estado "EN_ESPERA_EXCEPCIONES"
    Ejemplos:
      | Pagaduria   | Cedula       | Tasa   | Plazo | montoSolicitado | DiasHabilesIntereses | Ingresos  | descLey  | descNomina | Mes         | fechaDesembolso | primerNombre | segundoNombre | primerApellido | segundoApellido | fechaActual   | oficinaAsesor | Actividad    | TotalActivos | vlrCompasSaneamientos | TipoContrato | FechaIngreso | Correo                    | Celular      | departamento   | ciudad     | rutaPDF                                 | DestinoCredito     | genero | EstadoCivil | direccionResidencia | TipoVivienda | PapellidoReferencia | PnombreReferencia | TelefonoResidencia | TelefonoTrabajo | Codigo | AnoAnalisis | TipoDesen  | Banco                                  | AccountingSource   | AccountingName                                                          | FechaRegistro | Cartera1 | Saneamiento2 | Credito | nombresApellidos       | fechaNacimiento | Contacto                | lineaCredito      | estadoActual | page | codigo  | fechaExpedicion | estrado     | claseVivienda | posicionHogar   | nivelEscolaridad | cuotaHipotecaria | tipoDocNomina            | otrosIngresos | modalidadDesembolso      | tipoCliente | paisNacimiento | lugarDeNacimiento | nacionalidad | profesion   | mesesResidencia | numeroHijos | personasACargo | tipoPension | codigoProgramaNomina | fechaTerminacion | nitAfiliacion | tipoDocumento           | cargo | nombreBeneficario    | documentoBeneficiario | celularBeneficiario | monedaExtranjera | tipoTransanccion | productoBancario | banco       | numProducto | tipoProducto         | pais       | ciudadExt | monto  | moneda  | funcionarioPublico | recursosPublicos | expuestoPoliticamente | fechaExpuesto | Mes       | fecha        | AnnoAfetacion | fechaActual  | Banco                                              | vinculo     | plan     | tomarSeguroAP | nombresSeguroAP | parentescoSeguroAP | pNombreRefP | sNombreRefP | pApellidoRefP | sApellidoRefP | relacionRefP | celRefP      | pNombreRefF | sNombreRefF | pApellidoRefF | sApellidoRefF | relacionRefF | celRefF      | decisionExcepcion | NumRadicacion | tipocontratoAbacus         |
     ##@externaldata@./src/test/resources/data/AutomationData.xlsx@dataDigicredito
   |"COLFONDOS"   |"1017171608"   |"1.70"   |"50"   |"7500000"   |"50"   |"8500000"   |"250000"   |"300000"   |"Noviembre"   |"05/10/2021"   |"GERSON"   |""   |"ALONZO"   |"VARGAS"   |"25/Nov/2021"   |"Soacha"   |"Pensionado"   |"20500000"   |"0"   |"Jubilados"   |"10/03/2000"   |"thainer.perez@gmail.com"     |"3133421083"   |"Cundinamarca"   |"Anapoima"   |"src/test/resources/Data/PDFPRUEBA.pdf"   |"Educacion propia"   |"M"   |"Soltera/o"   |"Calle 2d #22-52"   |"Arriendo"   |"perez"   |"alejandro"   |"7210273"   |"9007146"   |"3112"   |"2021"   |"Efectivo"   |"Remanentes - 60237038927 - REMANENTE"   |"'ACRED','EGRESO'"    |"upper('Desembolso egreso'), upper('Desembolso activación de crédito')"   |29/10/2021   |"300000"   |"0"   |"86313"   |"GERSON ALONZO VARGAS"   |"15/02/1956"   |"Entidad donde trabaja"   |"Libre inversion"   |""   |""   |"12345"   |"06/08/1976"    |"Estrato 1"    |"Casa"   |"Jefe de hogar"   | "Universitario"    |"100000"   |"Desprendible de nómina"    |"5000000"   |"Pago masivo (efectivo)"    |"AAA"   |"colombia"   |"colombia"   |"colombiano"   |"ingeniero"    |"24"   |"2"      |"0"   |"pension"   |"123456"     |"30/12/2022"   |"123456"   |"Certificación laboral"   |"CEO"   |"Luis Perez Ramirez"   |"1234567890"   |"3183903022"   |"No"   |"Importaciones"   |"No"   |"Santander"   |"966855"   |"Inversiones en oro"    |"Alemania"   |"Berlin"   |"8500"   |"Euros"   |"No"   |"No"   |"No"   |"12/12/2008"   |"Febrero"   |"20/07/1963"   |"2022"   |"16/02/2022"   |"Bancolombia Remanentes - 60237038927 - REMANENTE"    |"Vinculado"   |"Plan 1"   |"No"   |"Juli Macias"   |"Prima"   |"maria"   |"camila"   |"lopez"   |"cardenas"   |"Amigo"   |"3204567894"   |"juan"   |"david"   |"reyes"   |"sanchez"   |"Hijo"   |"3204047804"   |"No"   |"92840"   |"Pensionado por Invalidez"|

  @Excepciones
  Esquema del escenario: Etapa de solicitud de excepciones
    Cuando busca el credito para retomar el estado actual <Cedula><estadoActual><page>
    Entonces se selecciona si se solicita las excepciones <decisionExcepcion>
#    Y se registran las excepciones
#      | tipoExcepcion  | detalleExcepcion             |
#      | Cartera cedida | Cesión de cartera            |
#      | Compliance     | Listas restrictivas          |
#      | Desprendible   | Desprendible con incapacidad |
#      | Desprendible   | Desprendible con vacaciones  |
#      | Tasa           | Tasa                         |
    Y valida el cambio de estado del credito <Cedula> con estado "EN_DECISION_SEGURO_AP"
    Ejemplos:
      | Pagaduria   | Cedula       | Tasa   | Plazo | montoSolicitado | DiasHabilesIntereses | Ingresos  | descLey  | descNomina | Mes         | fechaDesembolso | primerNombre | segundoNombre | primerApellido | segundoApellido | fechaActual   | oficinaAsesor | Actividad    | TotalActivos | vlrCompasSaneamientos | TipoContrato | FechaIngreso | Correo                    | Celular      | departamento   | ciudad     | rutaPDF                                 | DestinoCredito     | genero | EstadoCivil | direccionResidencia | TipoVivienda | PapellidoReferencia | PnombreReferencia | TelefonoResidencia | TelefonoTrabajo | Codigo | AnoAnalisis | TipoDesen  | Banco                                  | AccountingSource   | AccountingName                                                          | FechaRegistro | Cartera1 | Saneamiento2 | Credito | nombresApellidos       | fechaNacimiento | Contacto                | lineaCredito      | estadoActual | page | codigo  | fechaExpedicion | estrado     | claseVivienda | posicionHogar   | nivelEscolaridad | cuotaHipotecaria | tipoDocNomina            | otrosIngresos | modalidadDesembolso      | tipoCliente | paisNacimiento | lugarDeNacimiento | nacionalidad | profesion   | mesesResidencia | numeroHijos | personasACargo | tipoPension | codigoProgramaNomina | fechaTerminacion | nitAfiliacion | tipoDocumento           | cargo | nombreBeneficario    | documentoBeneficiario | celularBeneficiario | monedaExtranjera | tipoTransanccion | productoBancario | banco       | numProducto | tipoProducto         | pais       | ciudadExt | monto  | moneda  | funcionarioPublico | recursosPublicos | expuestoPoliticamente | fechaExpuesto | Mes       | fecha        | AnnoAfetacion | fechaActual  | Banco                                              | vinculo     | plan     | tomarSeguroAP | nombresSeguroAP | parentescoSeguroAP | pNombreRefP | sNombreRefP | pApellidoRefP | sApellidoRefP | relacionRefP | celRefP      | pNombreRefF | sNombreRefF | pApellidoRefF | sApellidoRefF | relacionRefF | celRefF      | decisionExcepcion | NumRadicacion | tipocontratoAbacus         |
     ##@externaldata@./src/test/resources/data/AutomationData.xlsx@dataDigicredito
   |"COLFONDOS"   |"1017171608"   |"1.70"   |"50"   |"7500000"   |"50"   |"8500000"   |"250000"   |"300000"   |"Noviembre"   |"05/10/2021"   |"GERSON"   |""   |"ALONZO"   |"VARGAS"   |"25/Nov/2021"   |"Soacha"   |"Pensionado"   |"20500000"   |"0"   |"Jubilados"   |"10/03/2000"   |"thainer.perez@gmail.com"     |"3133421083"   |"Cundinamarca"   |"Anapoima"   |"src/test/resources/Data/PDFPRUEBA.pdf"   |"Educacion propia"   |"M"   |"Soltera/o"   |"Calle 2d #22-52"   |"Arriendo"   |"perez"   |"alejandro"   |"7210273"   |"9007146"   |"3112"   |"2021"   |"Efectivo"   |"Remanentes - 60237038927 - REMANENTE"   |"'ACRED','EGRESO'"    |"upper('Desembolso egreso'), upper('Desembolso activación de crédito')"   |29/10/2021   |"300000"   |"0"   |"86313"   |"GERSON ALONZO VARGAS"   |"15/02/1956"   |"Entidad donde trabaja"   |"Libre inversion"   |""   |""   |"12345"   |"06/08/1976"    |"Estrato 1"    |"Casa"   |"Jefe de hogar"   | "Universitario"    |"100000"   |"Desprendible de nómina"    |"5000000"   |"Pago masivo (efectivo)"    |"AAA"   |"colombia"   |"colombia"   |"colombiano"   |"ingeniero"    |"24"   |"2"      |"0"   |"pension"   |"123456"     |"30/12/2022"   |"123456"   |"Certificación laboral"   |"CEO"   |"Luis Perez Ramirez"   |"1234567890"   |"3183903022"   |"No"   |"Importaciones"   |"No"   |"Santander"   |"966855"   |"Inversiones en oro"    |"Alemania"   |"Berlin"   |"8500"   |"Euros"   |"No"   |"No"   |"No"   |"12/12/2008"   |"Febrero"   |"20/07/1963"   |"2022"   |"16/02/2022"   |"Bancolombia Remanentes - 60237038927 - REMANENTE"    |"Vinculado"   |"Plan 1"   |"No"   |"Juli Macias"   |"Prima"   |"maria"   |"camila"   |"lopez"   |"cardenas"   |"Amigo"   |"3204567894"   |"juan"   |"david"   |"reyes"   |"sanchez"   |"Hijo"   |"3204047804"   |"No"   |"92840"   |"Pensionado por Invalidez"|

  @seguroAP
  Esquema del escenario: Etapa de seguro AP
    Cuando busca el credito para retomar el estado actual <Cedula><estadoActual><page>
    Entonces Se visualizan los beneficios del seguro
    Y Se selecciona el vinculo del seguro y el plan <vinculo><plan><tomarSeguroAP>
    #Y Se llenan los campos de tomador del seguro <nombresApellidos><Cedula><celular><correoElectronico><fechaNacimiento><departamento><ciudad><direccion>
    #Y Se registran los beneficiarios <nombresSeguroAP><parentescoSeguroAP>
    Y valida el cambio de estado del credito <Cedula> con estado "EN_REGISTRO_REFERENCIAS"
    Ejemplos:
      | Pagaduria   | Cedula       | Tasa   | Plazo | montoSolicitado | DiasHabilesIntereses | Ingresos  | descLey  | descNomina | Mes         | fechaDesembolso | primerNombre | segundoNombre | primerApellido | segundoApellido | fechaActual   | oficinaAsesor | Actividad    | TotalActivos | vlrCompasSaneamientos | TipoContrato | FechaIngreso | Correo                    | Celular      | departamento   | ciudad     | rutaPDF                                 | DestinoCredito     | genero | EstadoCivil | direccionResidencia | TipoVivienda | PapellidoReferencia | PnombreReferencia | TelefonoResidencia | TelefonoTrabajo | Codigo | AnoAnalisis | TipoDesen  | Banco                                  | AccountingSource   | AccountingName                                                          | FechaRegistro | Cartera1 | Saneamiento2 | Credito | nombresApellidos       | fechaNacimiento | Contacto                | lineaCredito      | estadoActual | page | codigo  | fechaExpedicion | estrado     | claseVivienda | posicionHogar   | nivelEscolaridad | cuotaHipotecaria | tipoDocNomina            | otrosIngresos | modalidadDesembolso      | tipoCliente | paisNacimiento | lugarDeNacimiento | nacionalidad | profesion   | mesesResidencia | numeroHijos | personasACargo | tipoPension | codigoProgramaNomina | fechaTerminacion | nitAfiliacion | tipoDocumento           | cargo | nombreBeneficario    | documentoBeneficiario | celularBeneficiario | monedaExtranjera | tipoTransanccion | productoBancario | banco       | numProducto | tipoProducto         | pais       | ciudadExt | monto  | moneda  | funcionarioPublico | recursosPublicos | expuestoPoliticamente | fechaExpuesto | Mes       | fecha        | AnnoAfetacion | fechaActual  | Banco                                              | vinculo     | plan     | tomarSeguroAP | nombresSeguroAP | parentescoSeguroAP | pNombreRefP | sNombreRefP | pApellidoRefP | sApellidoRefP | relacionRefP | celRefP      | pNombreRefF | sNombreRefF | pApellidoRefF | sApellidoRefF | relacionRefF | celRefF      | decisionExcepcion | NumRadicacion | tipocontratoAbacus         |
     ##@externaldata@./src/test/resources/data/AutomationData.xlsx@dataDigicredito
   |"COLFONDOS"   |"1017171608"   |"1.70"   |"50"   |"7500000"   |"50"   |"8500000"   |"250000"   |"300000"   |"Noviembre"   |"05/10/2021"   |"GERSON"   |""   |"ALONZO"   |"VARGAS"   |"25/Nov/2021"   |"Soacha"   |"Pensionado"   |"20500000"   |"0"   |"Jubilados"   |"10/03/2000"   |"thainer.perez@gmail.com"     |"3133421083"   |"Cundinamarca"   |"Anapoima"   |"src/test/resources/Data/PDFPRUEBA.pdf"   |"Educacion propia"   |"M"   |"Soltera/o"   |"Calle 2d #22-52"   |"Arriendo"   |"perez"   |"alejandro"   |"7210273"   |"9007146"   |"3112"   |"2021"   |"Efectivo"   |"Remanentes - 60237038927 - REMANENTE"   |"'ACRED','EGRESO'"    |"upper('Desembolso egreso'), upper('Desembolso activación de crédito')"   |29/10/2021   |"300000"   |"0"   |"86313"   |"GERSON ALONZO VARGAS"   |"15/02/1956"   |"Entidad donde trabaja"   |"Libre inversion"   |""   |""   |"12345"   |"06/08/1976"    |"Estrato 1"    |"Casa"   |"Jefe de hogar"   | "Universitario"    |"100000"   |"Desprendible de nómina"    |"5000000"   |"Pago masivo (efectivo)"    |"AAA"   |"colombia"   |"colombia"   |"colombiano"   |"ingeniero"    |"24"   |"2"      |"0"   |"pension"   |"123456"     |"30/12/2022"   |"123456"   |"Certificación laboral"   |"CEO"   |"Luis Perez Ramirez"   |"1234567890"   |"3183903022"   |"No"   |"Importaciones"   |"No"   |"Santander"   |"966855"   |"Inversiones en oro"    |"Alemania"   |"Berlin"   |"8500"   |"Euros"   |"No"   |"No"   |"No"   |"12/12/2008"   |"Febrero"   |"20/07/1963"   |"2022"   |"16/02/2022"   |"Bancolombia Remanentes - 60237038927 - REMANENTE"    |"Vinculado"   |"Plan 1"   |"No"   |"Juli Macias"   |"Prima"   |"maria"   |"camila"   |"lopez"   |"cardenas"   |"Amigo"   |"3204567894"   |"juan"   |"david"   |"reyes"   |"sanchez"   |"Hijo"   |"3204047804"   |"No"   |"92840"   |"Pensionado por Invalidez"|

  @referencias
  Esquema del escenario: Diligenciamiento de referencias personales y familiares
    Cuando busca el credito para retomar el estado actual <Cedula><estadoActual><page>
    Y Se ingresa la informacion de las referencias personales <pNombreRefP><sNombreRefP><pApellidoRefP><sApellidoRefP><relacionRefP><celRefP><departamento><ciudad>
    Y Se ingresa la informacion de las referencias familiares <pNombreRefF><sNombreRefF><pApellidoRefF><sApellidoRefF><relacionRefF><celRefF><departamento><ciudad>
    Y valida el cambio de estado del credito <Cedula> con estado "EN_REGISTRO_SEGURO_VIDA"
    Ejemplos:
      | Pagaduria   | Cedula       | Tasa   | Plazo | montoSolicitado | DiasHabilesIntereses | Ingresos  | descLey  | descNomina | Mes         | fechaDesembolso | primerNombre | segundoNombre | primerApellido | segundoApellido | fechaActual   | oficinaAsesor | Actividad    | TotalActivos | vlrCompasSaneamientos | TipoContrato | FechaIngreso | Correo                    | Celular      | departamento   | ciudad     | rutaPDF                                 | DestinoCredito     | genero | EstadoCivil | direccionResidencia | TipoVivienda | PapellidoReferencia | PnombreReferencia | TelefonoResidencia | TelefonoTrabajo | Codigo | AnoAnalisis | TipoDesen  | Banco                                  | AccountingSource   | AccountingName                                                          | FechaRegistro | Cartera1 | Saneamiento2 | Credito | nombresApellidos       | fechaNacimiento | Contacto                | lineaCredito      | estadoActual | page | codigo  | fechaExpedicion | estrado     | claseVivienda | posicionHogar   | nivelEscolaridad | cuotaHipotecaria | tipoDocNomina            | otrosIngresos | modalidadDesembolso      | tipoCliente | paisNacimiento | lugarDeNacimiento | nacionalidad | profesion   | mesesResidencia | numeroHijos | personasACargo | tipoPension | codigoProgramaNomina | fechaTerminacion | nitAfiliacion | tipoDocumento           | cargo | nombreBeneficario    | documentoBeneficiario | celularBeneficiario | monedaExtranjera | tipoTransanccion | productoBancario | banco       | numProducto | tipoProducto         | pais       | ciudadExt | monto  | moneda  | funcionarioPublico | recursosPublicos | expuestoPoliticamente | fechaExpuesto | Mes       | fecha        | AnnoAfetacion | fechaActual  | Banco                                              | vinculo     | plan     | tomarSeguroAP | nombresSeguroAP | parentescoSeguroAP | pNombreRefP | sNombreRefP | pApellidoRefP | sApellidoRefP | relacionRefP | celRefP      | pNombreRefF | sNombreRefF | pApellidoRefF | sApellidoRefF | relacionRefF | celRefF      | decisionExcepcion | NumRadicacion | tipocontratoAbacus         |
     ##@externaldata@./src/test/resources/data/AutomationData.xlsx@dataDigicredito
   |"COLFONDOS"   |"1017171608"   |"1.70"   |"50"   |"7500000"   |"50"   |"8500000"   |"250000"   |"300000"   |"Noviembre"   |"05/10/2021"   |"GERSON"   |""   |"ALONZO"   |"VARGAS"   |"25/Nov/2021"   |"Soacha"   |"Pensionado"   |"20500000"   |"0"   |"Jubilados"   |"10/03/2000"   |"thainer.perez@gmail.com"     |"3133421083"   |"Cundinamarca"   |"Anapoima"   |"src/test/resources/Data/PDFPRUEBA.pdf"   |"Educacion propia"   |"M"   |"Soltera/o"   |"Calle 2d #22-52"   |"Arriendo"   |"perez"   |"alejandro"   |"7210273"   |"9007146"   |"3112"   |"2021"   |"Efectivo"   |"Remanentes - 60237038927 - REMANENTE"   |"'ACRED','EGRESO'"    |"upper('Desembolso egreso'), upper('Desembolso activación de crédito')"   |29/10/2021   |"300000"   |"0"   |"86313"   |"GERSON ALONZO VARGAS"   |"15/02/1956"   |"Entidad donde trabaja"   |"Libre inversion"   |""   |""   |"12345"   |"06/08/1976"    |"Estrato 1"    |"Casa"   |"Jefe de hogar"   | "Universitario"    |"100000"   |"Desprendible de nómina"    |"5000000"   |"Pago masivo (efectivo)"    |"AAA"   |"colombia"   |"colombia"   |"colombiano"   |"ingeniero"    |"24"   |"2"      |"0"   |"pension"   |"123456"     |"30/12/2022"   |"123456"   |"Certificación laboral"   |"CEO"   |"Luis Perez Ramirez"   |"1234567890"   |"3183903022"   |"No"   |"Importaciones"   |"No"   |"Santander"   |"966855"   |"Inversiones en oro"    |"Alemania"   |"Berlin"   |"8500"   |"Euros"   |"No"   |"No"   |"No"   |"12/12/2008"   |"Febrero"   |"20/07/1963"   |"2022"   |"16/02/2022"   |"Bancolombia Remanentes - 60237038927 - REMANENTE"    |"Vinculado"   |"Plan 1"   |"No"   |"Juli Macias"   |"Prima"   |"maria"   |"camila"   |"lopez"   |"cardenas"   |"Amigo"   |"3204567894"   |"juan"   |"david"   |"reyes"   |"sanchez"   |"Hijo"   |"3204047804"   |"No"   |"92840"   |"Pensionado por Invalidez"|

  @seguroVida
  Esquema del escenario: Registrar beneficiarios seguro de vida
    Cuando busca el credito para retomar el estado actual <Cedula><estadoActual><page>
    Entonces diligencia minimo tres beneficiaros para el seguro de vida <nombreBeneficario><documentoBeneficiario><celularBeneficiario><departamento><ciudad>
    Y valida el cambio de estado del credito <Cedula> con estado "EN_REGISTRO_OPERACIONES_INTERNACIONALES"
    Ejemplos:
      | Pagaduria   | Cedula       | Tasa   | Plazo | montoSolicitado | DiasHabilesIntereses | Ingresos  | descLey  | descNomina | Mes         | fechaDesembolso | primerNombre | segundoNombre | primerApellido | segundoApellido | fechaActual   | oficinaAsesor | Actividad    | TotalActivos | vlrCompasSaneamientos | TipoContrato | FechaIngreso | Correo                    | Celular      | departamento   | ciudad     | rutaPDF                                 | DestinoCredito     | genero | EstadoCivil | direccionResidencia | TipoVivienda | PapellidoReferencia | PnombreReferencia | TelefonoResidencia | TelefonoTrabajo | Codigo | AnoAnalisis | TipoDesen  | Banco                                  | AccountingSource   | AccountingName                                                          | FechaRegistro | Cartera1 | Saneamiento2 | Credito | nombresApellidos       | fechaNacimiento | Contacto                | lineaCredito      | estadoActual | page | codigo  | fechaExpedicion | estrado     | claseVivienda | posicionHogar   | nivelEscolaridad | cuotaHipotecaria | tipoDocNomina            | otrosIngresos | modalidadDesembolso      | tipoCliente | paisNacimiento | lugarDeNacimiento | nacionalidad | profesion   | mesesResidencia | numeroHijos | personasACargo | tipoPension | codigoProgramaNomina | fechaTerminacion | nitAfiliacion | tipoDocumento           | cargo | nombreBeneficario    | documentoBeneficiario | celularBeneficiario | monedaExtranjera | tipoTransanccion | productoBancario | banco       | numProducto | tipoProducto         | pais       | ciudadExt | monto  | moneda  | funcionarioPublico | recursosPublicos | expuestoPoliticamente | fechaExpuesto | Mes       | fecha        | AnnoAfetacion | fechaActual  | Banco                                              | vinculo     | plan     | tomarSeguroAP | nombresSeguroAP | parentescoSeguroAP | pNombreRefP | sNombreRefP | pApellidoRefP | sApellidoRefP | relacionRefP | celRefP      | pNombreRefF | sNombreRefF | pApellidoRefF | sApellidoRefF | relacionRefF | celRefF      | decisionExcepcion | NumRadicacion | tipocontratoAbacus         |
     ##@externaldata@./src/test/resources/data/AutomationData.xlsx@dataDigicredito
   |"COLFONDOS"   |"1017171608"   |"1.70"   |"50"   |"7500000"   |"50"   |"8500000"   |"250000"   |"300000"   |"Noviembre"   |"05/10/2021"   |"GERSON"   |""   |"ALONZO"   |"VARGAS"   |"25/Nov/2021"   |"Soacha"   |"Pensionado"   |"20500000"   |"0"   |"Jubilados"   |"10/03/2000"   |"thainer.perez@gmail.com"     |"3133421083"   |"Cundinamarca"   |"Anapoima"   |"src/test/resources/Data/PDFPRUEBA.pdf"   |"Educacion propia"   |"M"   |"Soltera/o"   |"Calle 2d #22-52"   |"Arriendo"   |"perez"   |"alejandro"   |"7210273"   |"9007146"   |"3112"   |"2021"   |"Efectivo"   |"Remanentes - 60237038927 - REMANENTE"   |"'ACRED','EGRESO'"    |"upper('Desembolso egreso'), upper('Desembolso activación de crédito')"   |29/10/2021   |"300000"   |"0"   |"86313"   |"GERSON ALONZO VARGAS"   |"15/02/1956"   |"Entidad donde trabaja"   |"Libre inversion"   |""   |""   |"12345"   |"06/08/1976"    |"Estrato 1"    |"Casa"   |"Jefe de hogar"   | "Universitario"    |"100000"   |"Desprendible de nómina"    |"5000000"   |"Pago masivo (efectivo)"    |"AAA"   |"colombia"   |"colombia"   |"colombiano"   |"ingeniero"    |"24"   |"2"      |"0"   |"pension"   |"123456"     |"30/12/2022"   |"123456"   |"Certificación laboral"   |"CEO"   |"Luis Perez Ramirez"   |"1234567890"   |"3183903022"   |"No"   |"Importaciones"   |"No"   |"Santander"   |"966855"   |"Inversiones en oro"    |"Alemania"   |"Berlin"   |"8500"   |"Euros"   |"No"   |"No"   |"No"   |"12/12/2008"   |"Febrero"   |"20/07/1963"   |"2022"   |"16/02/2022"   |"Bancolombia Remanentes - 60237038927 - REMANENTE"    |"Vinculado"   |"Plan 1"   |"No"   |"Juli Macias"   |"Prima"   |"maria"   |"camila"   |"lopez"   |"cardenas"   |"Amigo"   |"3204567894"   |"juan"   |"david"   |"reyes"   |"sanchez"   |"Hijo"   |"3204047804"   |"No"   |"92840"   |"Pensionado por Invalidez"|

  @OperInternacionalesPEPS
  Esquema del escenario: Registrar operaciones internacionales y PEPS
    Cuando busca el credito para retomar el estado actual <Cedula><estadoActual><page>
    Y llena el formulario de operaciones internacionales <monedaExtranjera><tipoTransanccion><productoBancario><banco><numProducto><tipoProducto><pais><ciudadExt><montoSolicitado><moneda>
    Y llena el formulario de persona expuesta politicamente <funcionarioPublico><recursosPublicos><expuestoPoliticamente><fechaExpuesto>
    Y valida el cambio de estado del credito <Cedula> con estado "EN_ESPERA_FIRMA_DOCUMENTOS"
    Ejemplos:
      | Pagaduria   | Cedula       | Tasa   | Plazo | montoSolicitado | DiasHabilesIntereses | Ingresos  | descLey  | descNomina | Mes         | fechaDesembolso | primerNombre | segundoNombre | primerApellido | segundoApellido | fechaActual   | oficinaAsesor | Actividad    | TotalActivos | vlrCompasSaneamientos | TipoContrato | FechaIngreso | Correo                    | Celular      | departamento   | ciudad     | rutaPDF                                 | DestinoCredito     | genero | EstadoCivil | direccionResidencia | TipoVivienda | PapellidoReferencia | PnombreReferencia | TelefonoResidencia | TelefonoTrabajo | Codigo | AnoAnalisis | TipoDesen  | Banco                                  | AccountingSource   | AccountingName                                                          | FechaRegistro | Cartera1 | Saneamiento2 | Credito | nombresApellidos       | fechaNacimiento | Contacto                | lineaCredito      | estadoActual | page | codigo  | fechaExpedicion | estrado     | claseVivienda | posicionHogar   | nivelEscolaridad | cuotaHipotecaria | tipoDocNomina            | otrosIngresos | modalidadDesembolso      | tipoCliente | paisNacimiento | lugarDeNacimiento | nacionalidad | profesion   | mesesResidencia | numeroHijos | personasACargo | tipoPension | codigoProgramaNomina | fechaTerminacion | nitAfiliacion | tipoDocumento           | cargo | nombreBeneficario    | documentoBeneficiario | celularBeneficiario | monedaExtranjera | tipoTransanccion | productoBancario | banco       | numProducto | tipoProducto         | pais       | ciudadExt | monto  | moneda  | funcionarioPublico | recursosPublicos | expuestoPoliticamente | fechaExpuesto | Mes       | fecha        | AnnoAfetacion | fechaActual  | Banco                                              | vinculo     | plan     | tomarSeguroAP | nombresSeguroAP | parentescoSeguroAP | pNombreRefP | sNombreRefP | pApellidoRefP | sApellidoRefP | relacionRefP | celRefP      | pNombreRefF | sNombreRefF | pApellidoRefF | sApellidoRefF | relacionRefF | celRefF      | decisionExcepcion | NumRadicacion | tipocontratoAbacus         |
     ##@externaldata@./src/test/resources/data/AutomationData.xlsx@dataDigicredito
   |"COLFONDOS"   |"1017171608"   |"1.70"   |"50"   |"7500000"   |"50"   |"8500000"   |"250000"   |"300000"   |"Noviembre"   |"05/10/2021"   |"GERSON"   |""   |"ALONZO"   |"VARGAS"   |"25/Nov/2021"   |"Soacha"   |"Pensionado"   |"20500000"   |"0"   |"Jubilados"   |"10/03/2000"   |"thainer.perez@gmail.com"     |"3133421083"   |"Cundinamarca"   |"Anapoima"   |"src/test/resources/Data/PDFPRUEBA.pdf"   |"Educacion propia"   |"M"   |"Soltera/o"   |"Calle 2d #22-52"   |"Arriendo"   |"perez"   |"alejandro"   |"7210273"   |"9007146"   |"3112"   |"2021"   |"Efectivo"   |"Remanentes - 60237038927 - REMANENTE"   |"'ACRED','EGRESO'"    |"upper('Desembolso egreso'), upper('Desembolso activación de crédito')"   |29/10/2021   |"300000"   |"0"   |"86313"   |"GERSON ALONZO VARGAS"   |"15/02/1956"   |"Entidad donde trabaja"   |"Libre inversion"   |""   |""   |"12345"   |"06/08/1976"    |"Estrato 1"    |"Casa"   |"Jefe de hogar"   | "Universitario"    |"100000"   |"Desprendible de nómina"    |"5000000"   |"Pago masivo (efectivo)"    |"AAA"   |"colombia"   |"colombia"   |"colombiano"   |"ingeniero"    |"24"   |"2"      |"0"   |"pension"   |"123456"     |"30/12/2022"   |"123456"   |"Certificación laboral"   |"CEO"   |"Luis Perez Ramirez"   |"1234567890"   |"3183903022"   |"No"   |"Importaciones"   |"No"   |"Santander"   |"966855"   |"Inversiones en oro"    |"Alemania"   |"Berlin"   |"8500"   |"Euros"   |"No"   |"No"   |"No"   |"12/12/2008"   |"Febrero"   |"20/07/1963"   |"2022"   |"16/02/2022"   |"Bancolombia Remanentes - 60237038927 - REMANENTE"    |"Vinculado"   |"Plan 1"   |"No"   |"Juli Macias"   |"Prima"   |"maria"   |"camila"   |"lopez"   |"cardenas"   |"Amigo"   |"3204567894"   |"juan"   |"david"   |"reyes"   |"sanchez"   |"Hijo"   |"3204047804"   |"No"   |"92840"   |"Pensionado por Invalidez"|

  @firmaDocumentos
  Esquema del escenario: Realiza la firma final de documentos
    Cuando busca el credito para retomar el estado actual <Cedula><estadoActual><page>
   # Y consulta el codigo OTP <Cedula>
    Y descarga los documentos a firmar
    Entonces diligencia el tipo de documento y adjunta el archivo <rutaPDF>
    #Y valida el cambio de estado del credito <Cedula> con estado "EN_SIMULACION_FINAL_ASESOR"
    Ejemplos:
      | Pagaduria   | Cedula       | Tasa   | Plazo | montoSolicitado | DiasHabilesIntereses | Ingresos  | descLey  | descNomina | Mes         | fechaDesembolso | primerNombre | segundoNombre | primerApellido | segundoApellido | fechaActual   | oficinaAsesor | Actividad    | TotalActivos | vlrCompasSaneamientos | TipoContrato | FechaIngreso | Correo                    | Celular      | departamento   | ciudad     | rutaPDF                                 | DestinoCredito     | genero | EstadoCivil | direccionResidencia | TipoVivienda | PapellidoReferencia | PnombreReferencia | TelefonoResidencia | TelefonoTrabajo | Codigo | AnoAnalisis | TipoDesen  | Banco                                  | AccountingSource   | AccountingName                                                          | FechaRegistro | Cartera1 | Saneamiento2 | Credito | nombresApellidos       | fechaNacimiento | Contacto                | lineaCredito      | estadoActual | page | codigo  | fechaExpedicion | estrado     | claseVivienda | posicionHogar   | nivelEscolaridad | cuotaHipotecaria | tipoDocNomina            | otrosIngresos | modalidadDesembolso      | tipoCliente | paisNacimiento | lugarDeNacimiento | nacionalidad | profesion   | mesesResidencia | numeroHijos | personasACargo | tipoPension | codigoProgramaNomina | fechaTerminacion | nitAfiliacion | tipoDocumento           | cargo | nombreBeneficario    | documentoBeneficiario | celularBeneficiario | monedaExtranjera | tipoTransanccion | productoBancario | banco       | numProducto | tipoProducto         | pais       | ciudadExt | monto  | moneda  | funcionarioPublico | recursosPublicos | expuestoPoliticamente | fechaExpuesto | Mes       | fecha        | AnnoAfetacion | fechaActual  | Banco                                              | vinculo     | plan     | tomarSeguroAP | nombresSeguroAP | parentescoSeguroAP | pNombreRefP | sNombreRefP | pApellidoRefP | sApellidoRefP | relacionRefP | celRefP      | pNombreRefF | sNombreRefF | pApellidoRefF | sApellidoRefF | relacionRefF | celRefF      | decisionExcepcion | NumRadicacion | tipocontratoAbacus         |
     ##@externaldata@./src/test/resources/data/AutomationData.xlsx@dataDigicredito
   |"COLFONDOS"   |"1017171608"   |"1.70"   |"50"   |"7500000"   |"50"   |"8500000"   |"250000"   |"300000"   |"Noviembre"   |"05/10/2021"   |"GERSON"   |""   |"ALONZO"   |"VARGAS"   |"25/Nov/2021"   |"Soacha"   |"Pensionado"   |"20500000"   |"0"   |"Jubilados"   |"10/03/2000"   |"thainer.perez@gmail.com"     |"3133421083"   |"Cundinamarca"   |"Anapoima"   |"src/test/resources/Data/PDFPRUEBA.pdf"   |"Educacion propia"   |"M"   |"Soltera/o"   |"Calle 2d #22-52"   |"Arriendo"   |"perez"   |"alejandro"   |"7210273"   |"9007146"   |"3112"   |"2021"   |"Efectivo"   |"Remanentes - 60237038927 - REMANENTE"   |"'ACRED','EGRESO'"    |"upper('Desembolso egreso'), upper('Desembolso activación de crédito')"   |29/10/2021   |"300000"   |"0"   |"86313"   |"GERSON ALONZO VARGAS"   |"15/02/1956"   |"Entidad donde trabaja"   |"Libre inversion"   |""   |""   |"12345"   |"06/08/1976"    |"Estrato 1"    |"Casa"   |"Jefe de hogar"   | "Universitario"    |"100000"   |"Desprendible de nómina"    |"5000000"   |"Pago masivo (efectivo)"    |"AAA"   |"colombia"   |"colombia"   |"colombiano"   |"ingeniero"    |"24"   |"2"      |"0"   |"pension"   |"123456"     |"30/12/2022"   |"123456"   |"Certificación laboral"   |"CEO"   |"Luis Perez Ramirez"   |"1234567890"   |"3183903022"   |"No"   |"Importaciones"   |"No"   |"Santander"   |"966855"   |"Inversiones en oro"    |"Alemania"   |"Berlin"   |"8500"   |"Euros"   |"No"   |"No"   |"No"   |"12/12/2008"   |"Febrero"   |"20/07/1963"   |"2022"   |"16/02/2022"   |"Bancolombia Remanentes - 60237038927 - REMANENTE"    |"Vinculado"   |"Plan 1"   |"No"   |"Juli Macias"   |"Prima"   |"maria"   |"camila"   |"lopez"   |"cardenas"   |"Amigo"   |"3204567894"   |"juan"   |"david"   |"reyes"   |"sanchez"   |"Hijo"   |"3204047804"   |"No"   |"92840"   |"Pensionado por Invalidez"|
